# config.yaml

paths:
  images_dir: "data\\images"                    # If your images are in this folder, otherwise adjust accordingly.
  annotations_dir: "data\\annotations"          # Directory containing the annotations.
  train_images_dir: "data\\images\\train"        # Dossier des images d'entraînement.
  val_images_dir: "data\\images\\val"            # Dossier des images de validation.
  test_images_dir: "data\\images\\test" 
  train_annotations_file: "data/annotations/instances_train_objects_in_water.json"
  val_annotations_file: "data/annotations/instances_val_objects_in_water.json"
  test_annotations_file: "data/annotations/instances_test_objects_in_water.json"

  yolo_dataset_dir: "data/yolo"                 # Folder where you will convert annotations for YOLO.
  trained_model_dir: "models/"                   # Où sauvegarder les modèles entraînés.
  export_model_dir: "outputs/exports/"           # Où sauvegarder les modèles exportés.
  output_videos_dir: "outputs/videos/"           # Vidéos de suivi (tracking).
  log_file: "log.txt"                            # Fichier log à la racine.

yolo:
  pretrained_model: "yolov8n.pt"                 # Modèle YOLOv8 de base.
  epochs: 20
  batch_size: 16
  img_size: 640

tracking:
  input_video: "assets/input_video.mp4"          # Déplace la vidéo d'entrée dans `assets`, plus logique.
  output_video: "outputs/videos/tracked_video.mp4" # Vidéo de sortie.

visualization:
  output_dir: "outputs/visualizations/"          # Dossier pour les visualisations d'annotations.

evaluation:
  val_images_folder: "data/images/val"
  val_labels_folder: "data/yolo_labels/val"
  best_model_path: "outputs/exports/yolov8_best.pt"
  metrics_output_file: "outputs/evaluation/metrics.json"
  confidence_threshold: 0.5
  iou_threshold: 0.5                            # Seuil IoU pour la suppression non maximale (NMS).